name: futgres
description: A new Flutter project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.6
  shared_preferences: ^2.2.1
  permission_handler: ^11.0.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  get_it: ^7.6.4

dev_dependencies:
  flutter_lints: ^2.0.3
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - images/background.png
    - images/logo.png
    - images/logotype.png
